/**
 * Integration test: sign_transaction end-to-end.
 *
 * Requires:
 *  - Docker (Postgres container via testcontainers)
 *  - Go toolchain (builds the signer binary; must include the new
 *    /internal/sign/transaction endpoint added in P6)
 *
 * If Go is absent the signer helper returns null and the suite is skipped.
 *
 * Recovery verification:
 *  - For EIP-1559 the signing hash is keccak256(unsignedTxBytes) since the
 *    unsigned tx already contains the type byte (0x02) + the 9-field RLP.
 *    We use @noble/hashes/sha3 (keccak_256) and @noble/curves/secp256k1 to
 *    recover the sender address from (r, s, v, signingHash) using only the
 *    signedTransaction hex bytes — NOT signerReceipt.publicKey.
 *    This is a TRUE cryptographic recovery: a signer bug that produces a
 *    valid signature over wrong fields would produce a different signing hash
 *    and thus a wrong recovered address, causing the assertion to fail.
 *
 *  - For legacy EIP-155 and for methodSelector extraction, we rely on:
 *    (a) the signer receipt publicKey (compressed pubkey hex) from which we
 *        derive the Ethereum address via keccak256(uncompress(pub)[1:])[12:],
 *    (b) comparing that address to the one returned by create_private_keys.
 *    This is the parity guard: the signer signs with the correct key.
 *
 * Note: viem is not installed in this workspace; recovery is implemented via
 * @noble/curves + @noble/hashes which are already present.
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { secp256k1 } from "@noble/curves/secp256k1";
import { keccak_256 } from "@noble/hashes/sha3";
import { bytesToHex, hexToBytes } from "@noble/hashes/utils";
import { createApp } from "../src/app";
import { startTestDb, type TestDb } from "./helpers/pg";
import { seedStamper, stampedRequest } from "./helpers/stamp";
import { startTestSigner, type TestSigner } from "./helpers/signer";
import type { ApiKeyStamper } from "@turnkey/api-key-stamper";

// ---------------------------------------------------------------------------
// Fixed unsigned EVM transaction hex strings
// ---------------------------------------------------------------------------

/**
 * Fixed EIP-1559 unsigned tx (type 0x02) for Sepolia (chainId=11155111):
 *   nonce=0, maxPriorityFeePerGas=1e9, maxFeePerGas=1e9, gas=21000,
 *   to=0x000000000000000000000000000000000000dEaD, value=0, data=[], accessList=[]
 *
 * Generated by: 0x02 || rlp([chainId, nonce, maxPriorityFeePerGas, maxFeePerGas, gas, to, value, data, accessList])
 */
const EIP1559_UNSIGNED_TX =
  "0x02ea83aa36a780843b9aca00843b9aca0082520894000000000000000000000000000000000000dead8080c0";

/**
 * Fixed legacy EIP-155 unsigned tx for Sepolia (chainId=11155111):
 *   nonce=0, gasPrice=1e9, gas=21000, to=0x...dEaD, value=0, data=[]
 *   9-field form: rlp([nonce, gasPrice, gas, to, value, data, chainId, 0, 0])
 */
const LEGACY_UNSIGNED_TX =
  "0xe680843b9aca0082520894000000000000000000000000000000000000dead808083aa36a78080";

/**
 * EIP-1559 unsigned tx with calldata starting 0x7fea8778 (sweep-like selector):
 *   nonce=1, gas=100000, to=0x...dEaD, value=0
 *   data=0x7fea8778abcdef010203 (10 bytes; methodSelector = 0x7fea8778)
 *
 * Generated the same way as EIP1559_UNSIGNED_TX but with Data set.
 */
const CALLDATA_UNSIGNED_TX =
  "0x02f583aa36a701843b9aca00843b9aca00830186a094000000000000000000000000000000000000dead808a7fea8778abcdef010203c0";

// ---------------------------------------------------------------------------
// Shared state
// ---------------------------------------------------------------------------
let tdb: TestDb;
let signer: TestSigner | null = null;
let app: ReturnType<typeof createApp>;
let organizationId: string;
let stamper: ApiKeyStamper;
let goAvailable = true;

beforeAll(async () => {
  tdb = await startTestDb();
  ({ organizationId, stamper } = await seedStamper(tdb.db));

  // Build the signer fresh so it includes /internal/sign/transaction (P6).
  signer = await startTestSigner(false);

  if (!signer) {
    goAvailable = false;
    app = createApp({ db: tdb.db, signerBaseUrl: "http://127.0.0.1:1", policyBypassAllowed: true });
    return;
  }

  app = createApp({ db: tdb.db, signerBaseUrl: signer.baseUrl, policyBypassAllowed: true });
});

afterAll(async () => {
  signer?.stop();
  await tdb.stop();
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeCreateKeyBody(name: string) {
  return {
    type: "ACTIVITY_TYPE_CREATE_PRIVATE_KEYS_V2",
    organizationId,
    timestampMs: String(Date.now()),
    parameters: { name, curve: "CURVE_SECP256K1", addressFormats: [] },
  };
}

function makeSignTxBody(signWith: string, unsignedTransaction: string, extra: Record<string, unknown> = {}) {
  return {
    type: "ACTIVITY_TYPE_SIGN_TRANSACTION_V2",
    organizationId,
    timestampMs: String(Date.now()),
    parameters: {
      signWith,
      unsignedTransaction,
      type: "TRANSACTION_TYPE_ETHEREUM",
      ...extra,
    },
  };
}

async function submitCreateKey(name = `signtx-key-${Date.now()}`) {
  const body = makeCreateKeyBody(name);
  const init = await stampedRequest(stamper, body);
  const res = await app.request("/public/v1/submit/create_private_keys", init);
  expect(res.status).toBe(200);
  const json = (await res.json()) as {
    activity: {
      status: string;
      result: {
        createPrivateKeysResult: {
          privateKeyIds: string[];
          addresses: { address: string }[];
        };
      };
    };
  };
  expect(json.activity.status).toBe("ACTIVITY_STATUS_COMPLETED");
  const privateKeyId = json.activity.result.createPrivateKeysResult.privateKeyIds[0];
  const address = json.activity.result.createPrivateKeysResult.addresses[0].address;
  return { privateKeyId, address };
}

async function submitSignTx(
  signWith: string,
  unsignedTransaction: string,
  extra: Record<string, unknown> = {},
) {
  const body = makeSignTxBody(signWith, unsignedTransaction, extra);
  const init = await stampedRequest(stamper, body);
  return app.request("/public/v1/submit/sign_transaction", init);
}

/**
 * Derive the Ethereum address from a compressed secp256k1 public key hex.
 * Ethereum address = keccak256(uncompressed_pubkey[1:])[12:]
 */
function addressFromCompressedPubkey(compressedPubHex: string): string {
  const compressedPub = hexToBytes(compressedPubHex);
  const point = secp256k1.ProjectivePoint.fromHex(compressedPub);
  const uncompressed = point.toRawBytes(false); // 65 bytes: 0x04 || x || y
  const pubBody = uncompressed.slice(1); // 64 bytes: x || y
  const hash = keccak_256(pubBody);
  const addrBytes = hash.slice(12); // last 20 bytes
  return "0x" + bytesToHex(addrBytes);
}

/**
 * Derive the Ethereum address from the signer receipt public key.
 * Used for legacy and secondary assertions.
 */
function addressFromSignerReceipt(signerReceiptPublicKey: string): string {
  return addressFromCompressedPubkey(signerReceiptPublicKey);
}

// ---------------------------------------------------------------------------
// Minimal RLP decoder — sufficient to extract last N big-integer items from
// a top-level RLP list (used for EIP-1559 signed tx parsing).
// ---------------------------------------------------------------------------

/** Decode the length and payload offset of a single RLP item starting at `buf[offset]`.
 *  Returns [contentStart, contentLength, totalItemLength]. */
function rlpItemBounds(buf: Uint8Array, offset: number): [number, number, number] {
  const prefix = buf[offset];
  if (prefix <= 0x7f) {
    // Single-byte string (the byte itself is the value).
    return [offset, 1, 1];
  }
  if (prefix <= 0xb7) {
    // Short string: 0x80..0xb7 — next (prefix - 0x80) bytes are content.
    const len = prefix - 0x80;
    return [offset + 1, len, 1 + len];
  }
  if (prefix <= 0xbf) {
    // Long string: 0xb8..0xbf — next (prefix - 0xb7) bytes encode the content length.
    const lenLen = prefix - 0xb7;
    let len = 0;
    for (let i = 0; i < lenLen; i++) len = (len << 8) | buf[offset + 1 + i];
    return [offset + 1 + lenLen, len, 1 + lenLen + len];
  }
  if (prefix <= 0xf7) {
    // Short list: 0xc0..0xf7 — next (prefix - 0xc0) bytes are list payload.
    const len = prefix - 0xc0;
    return [offset + 1, len, 1 + len];
  }
  // Long list: 0xf8..0xff — next (prefix - 0xf7) bytes encode the payload length.
  const lenLen = prefix - 0xf7;
  let len = 0;
  for (let i = 0; i < lenLen; i++) len = (len << 8) | buf[offset + 1 + i];
  return [offset + 1 + lenLen, len, 1 + lenLen + len];
}

/** Decode a RLP big-integer item (short string encoding) as a BigInt. */
function rlpItemToBigInt(buf: Uint8Array, contentStart: number, contentLen: number): bigint {
  let v = 0n;
  for (let i = 0; i < contentLen; i++) {
    v = (v << 8n) | BigInt(buf[contentStart + i]);
  }
  return v;
}

/**
 * Recover the sender Ethereum address from a signed EIP-1559 transaction.
 *
 * Strategy:
 *  1. signingHash = keccak256(hexToBytes(unsignedTxHex))
 *     The unsigned EIP-1559 tx already IS the signing preimage:
 *       0x02 || rlp([chainId, nonce, maxPriorityFee, maxFee, gas, to, value, data, accessList])
 *     go-ethereum computes the signing hash as keccak256(type_byte || rlp_payload),
 *     which is exactly keccak256(all bytes of the unsigned tx).
 *
 *  2. Parse the signed tx to extract yParity, r, s.
 *     Signed EIP-1559 format: 0x02 || rlp([chainId, nonce, maxPriorityFee, maxFee,
 *       gas, to, value, data, accessList, yParity, r, s])  (12 items)
 *     We iterate the list items and capture the last 3.
 *
 *  3. Use secp256k1 signature recovery: recoverPublicKey(signingHash, sig, recovery).
 *
 *  4. Derive the Ethereum address from the recovered uncompressed public key.
 *
 * This is a TRUE cryptographic check: a signer that signed different fields than
 * requested would produce a wrong signing hash → wrong recovered address → test fails.
 */
function recoverSenderFromEIP1559Tx(
  signedTxHex: string,
  unsignedTxHex: string,
): string {
  // Step 1: compute the signing hash from the ORIGINAL unsigned tx bytes.
  const unsignedBytes = hexToBytes(unsignedTxHex.replace(/^0x/i, ""));
  const signingHash = keccak_256(unsignedBytes);

  // Step 2: parse r/s/yParity from the signed tx.
  const signedBytes = hexToBytes(signedTxHex.replace(/^0x/i, ""));
  // First byte is the EIP-2718 type byte (0x02); remainder is the RLP list.
  if (signedBytes[0] !== 0x02) {
    throw new Error(`Expected EIP-1559 type byte 0x02, got 0x${signedBytes[0].toString(16)}`);
  }
  const rlpPayload = signedBytes.slice(1);

  // Decode the top-level list.
  const [listContentStart, listContentLen] = rlpItemBounds(rlpPayload, 0);

  // Iterate all items in the list to find the last 3 (yParity, r, s).
  const items: Array<{ contentStart: number; contentLen: number }> = [];
  let pos = listContentStart;
  const listEnd = listContentStart + listContentLen;
  while (pos < listEnd) {
    const [cs, cl, total] = rlpItemBounds(rlpPayload, pos);
    items.push({ contentStart: cs, contentLen: cl });
    pos += total;
  }

  if (items.length < 3) {
    throw new Error(`Expected at least 3 RLP items in signed EIP-1559 tx list, got ${items.length}`);
  }

  const yParityItem = items[items.length - 3];
  const rItem = items[items.length - 2];
  const sItem = items[items.length - 1];

  const yParity = Number(rlpItemToBigInt(rlpPayload, yParityItem.contentStart, yParityItem.contentLen));
  const rBig = rlpItemToBigInt(rlpPayload, rItem.contentStart, rItem.contentLen);
  const sBig = rlpItemToBigInt(rlpPayload, sItem.contentStart, sItem.contentLen);

  if (yParity !== 0 && yParity !== 1) {
    throw new Error(`Unexpected yParity value ${yParity}`);
  }

  // Step 3: recover the public key.
  // addRecoveryBit attaches the yParity recovery bit to produce an ECDSASigRecovered,
  // then recoverPublicKey(msgHash) uses that recovery bit internally.
  const sig = new secp256k1.Signature(rBig, sBig).addRecoveryBit(yParity);
  const recoveredPoint = sig.recoverPublicKey(signingHash);
  const uncompressed = recoveredPoint.toRawBytes(false); // 65 bytes: 0x04 || x || y
  const pubBody = uncompressed.slice(1); // 64 bytes
  const addrHash = keccak_256(pubBody);
  return "0x" + bytesToHex(addrHash.slice(12)); // last 20 bytes
}

const BARE_64HEX_RE = /"([0-9a-f]{64})"/i;
function assertNoPlaintextKey(value: unknown): void {
  const str = JSON.stringify(value);
  const match = BARE_64HEX_RE.exec(str);
  if (match) {
    const forbidden = ["privateKeyHex", "rawPrivateKey", "privateKeyMaterial", "plaintext"];
    for (const f of forbidden) {
      if (str.includes(`"${f}"`)) {
        throw new Error(`Response contains forbidden plaintext field "${f}": ${str.slice(0, 300)}`);
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
describe("sign_transaction end-to-end", () => {
  it("skip message when go is absent", () => {
    if (!goAvailable) {
      console.warn("[signTransaction.int.test] Go toolchain not available — signer integration tests skipped.");
    }
    expect(true).toBe(true);
  });

  // ---------------------------------------------------------------------------
  // 1. EIP-1559 parity guard: recover sender FROM the signed-tx bytes
  // ---------------------------------------------------------------------------
  it("EIP-1559: COMPLETED + signedTransaction + sender recovered from signed-tx bytes matches key address", async () => {
    if (!goAvailable) return;

    const { privateKeyId, address } = await submitCreateKey("p6-eip1559-test");

    const res = await submitSignTx(privateKeyId, EIP1559_UNSIGNED_TX);
    expect(res.status).toBe(200);

    const json = (await res.json()) as {
      activity: {
        status: string;
        result: {
          signTransactionResult: {
            signedTransaction: string;
            fields: Record<string, unknown>;
            signerReceipt: { publicKey: string; keyId: string; payloadHash: string; signatureHash: string; signerBuildId: string };
          };
        };
        failure: unknown;
      };
    };

    expect(json.activity.status).toBe("ACTIVITY_STATUS_COMPLETED");
    expect(json.activity.failure).toBeNull();

    const { signedTransaction, fields, signerReceipt } = json.activity.result.signTransactionResult;

    // Turnkey wire format: signedTransaction is hex WITHOUT 0x, EIP-1559 type
    // byte 0x02 first (frozen contract — see tools/compat-harness/wire-contract.md).
    expect(signedTransaction).toMatch(/^02/);
    expect(signedTransaction).not.toMatch(/^0x/);
    expect(typeof signedTransaction).toBe("string");

    // PRIMARY CHECK (HIGH review fix): recover the sender address from the
    // signed-tx bytes + the original unsigned tx (as signing hash preimage).
    // This DOES NOT use signerReceipt.publicKey — it is a true cryptographic
    // recovery from the actual signature bytes embedded in signedTransaction.
    // A signer bug that signed different fields (wrong chainId, wrong to, etc.)
    // would change the RLP encoding → different signing hash → wrong recovered
    // address → this assertion fails. Non-tautological by construction.
    const recoveredAddr = recoverSenderFromEIP1559Tx(signedTransaction, EIP1559_UNSIGNED_TX);
    expect(recoveredAddr.toLowerCase()).toBe(address.toLowerCase());

    // SANITY sub-assertion: flipping one byte in the signed tx must NOT recover
    // to the same address (proves the check actually binds the bytes).
    // We flip a byte in the middle of the r/s region (well past the 0x02 type
    // byte and the RLP list header) to produce an invalid signature.
    const signedBytes = hexToBytes(signedTransaction.replace(/^0x/i, ""));
    const corrupted = new Uint8Array(signedBytes);
    // Flip a byte near the end (within r or s) — last 20 bytes are in s.
    corrupted[corrupted.length - 10] ^= 0xff;
    const corruptedHex = "0x" + bytesToHex(corrupted);
    let corruptedRecovered: string | null = null;
    try {
      corruptedRecovered = recoverSenderFromEIP1559Tx(corruptedHex, EIP1559_UNSIGNED_TX);
    } catch {
      // A corrupted signature may be unrecoverable — that's also a pass.
      corruptedRecovered = null;
    }
    // Either recovery threw (corrupt sig) OR it recovered a DIFFERENT address.
    if (corruptedRecovered !== null) {
      expect(corruptedRecovered.toLowerCase()).not.toBe(address.toLowerCase());
    }

    // SECONDARY CHECK: signerReceipt.publicKey → Ethereum address also matches.
    // This cross-validates that the signer used the expected key.
    const receiptAddr = addressFromSignerReceipt(signerReceipt.publicKey);
    expect(receiptAddr.toLowerCase()).toBe(address.toLowerCase());

    // fields must contain expected values
    expect(fields.chainId).toMatch(/^0x/);
    // to = 0x000...dEaD (case-insensitive)
    expect((fields.to as string).toLowerCase()).toBe(
      "0x000000000000000000000000000000000000dead",
    );
    expect(fields.nonce).toBe(0);
    expect(fields.gas).toBe(21000);
    expect(fields.value).toBe("0x0");
    expect(fields.methodSelector).toBeFalsy(); // empty data → no selector

    // signer receipt checks
    expect(typeof signerReceipt.payloadHash).toBe("string");
    expect(typeof signerReceipt.signatureHash).toBe("string");
    expect(typeof signerReceipt.signerBuildId).toBe("string");

    assertNoPlaintextKey(json);
  });

  // ---------------------------------------------------------------------------
  // 2. Legacy EIP-155: signs + recovers to key address
  // ---------------------------------------------------------------------------
  it("Legacy EIP-155: COMPLETED + signedTransaction + recovers to key address", async () => {
    if (!goAvailable) return;

    const { privateKeyId, address } = await submitCreateKey("p6-legacy-test");

    const res = await submitSignTx(privateKeyId, LEGACY_UNSIGNED_TX);
    expect(res.status).toBe(200);

    const json = (await res.json()) as {
      activity: {
        status: string;
        result: {
          signTransactionResult: {
            signedTransaction: string;
            signerReceipt: { publicKey: string };
          };
        };
        failure: unknown;
      };
    };

    expect(json.activity.status).toBe("ACTIVITY_STATUS_COMPLETED");
    expect(json.activity.failure).toBeNull();

    const { signedTransaction, signerReceipt } = json.activity.result.signTransactionResult;
    expect(typeof signedTransaction).toBe("string");
    // Turnkey wire format: hex WITHOUT 0x (frozen contract).
    expect(signedTransaction).not.toMatch(/^0x/);

    // Legacy signed tx should NOT start with the 0x02 type byte (no type byte);
    // legacy RLP begins with the list header (0xf8/0xf9…).
    expect(signedTransaction).not.toMatch(/^02/);

    // Parity guard: derive address from signer receipt public key.
    const derivedAddr = addressFromSignerReceipt(signerReceipt.publicKey);
    expect(derivedAddr.toLowerCase()).toBe(address.toLowerCase());

    assertNoPlaintextKey(json);
  });

  // ---------------------------------------------------------------------------
  // 3. methodSelector extraction from calldata
  // ---------------------------------------------------------------------------
  it("calldata → fields.methodSelector === '0x7fea8778'", async () => {
    if (!goAvailable) return;

    const { privateKeyId } = await submitCreateKey("p6-selector-test");

    const res = await submitSignTx(privateKeyId, CALLDATA_UNSIGNED_TX);
    expect(res.status).toBe(200);

    const json = (await res.json()) as {
      activity: {
        status: string;
        result: {
          signTransactionResult: {
            signedTransaction: string;
            fields: { methodSelector?: string; data: string };
          };
        };
        failure: unknown;
      };
    };

    expect(json.activity.status).toBe("ACTIVITY_STATUS_COMPLETED");
    expect(json.activity.failure).toBeNull();

    const { fields } = json.activity.result.signTransactionResult;
    expect(fields.methodSelector).toBe("0x7fea8778");
    expect((fields.data as string).startsWith("0x7fea8778")).toBe(true);
  });

  // ---------------------------------------------------------------------------
  // 4a. signWith by private-key id and by Ethereum address — both resolve
  // ---------------------------------------------------------------------------
  it("signWith by private-key id resolves and signs", async () => {
    if (!goAvailable) return;

    const { privateKeyId, address } = await submitCreateKey("p6-by-id-test");
    const res = await submitSignTx(privateKeyId, EIP1559_UNSIGNED_TX);
    expect(res.status).toBe(200);

    const json = (await res.json()) as {
      activity: {
        status: string;
        result: { signTransactionResult: { signerReceipt: { publicKey: string } } };
        failure: unknown;
      };
    };
    expect(json.activity.status).toBe("ACTIVITY_STATUS_COMPLETED");
    expect(json.activity.failure).toBeNull();

    const derivedAddr = addressFromSignerReceipt(
      json.activity.result.signTransactionResult.signerReceipt.publicKey,
    );
    expect(derivedAddr.toLowerCase()).toBe(address.toLowerCase());
  });

  it("signWith by Ethereum address resolves and signs", async () => {
    if (!goAvailable) return;

    const { address } = await submitCreateKey("p6-by-addr-test");
    const res = await submitSignTx(address, EIP1559_UNSIGNED_TX);
    expect(res.status).toBe(200);

    const json = (await res.json()) as {
      activity: {
        status: string;
        result: { signTransactionResult: { signerReceipt: { publicKey: string } } };
        failure: unknown;
      };
    };
    expect(json.activity.status).toBe("ACTIVITY_STATUS_COMPLETED");
    expect(json.activity.failure).toBeNull();

    const derivedAddr = addressFromSignerReceipt(
      json.activity.result.signTransactionResult.signerReceipt.publicKey,
    );
    expect(derivedAddr.toLowerCase()).toBe(address.toLowerCase());
  });

  // ---------------------------------------------------------------------------
  // 4b. Unknown signWith → FAILED PRIVATE_KEY_NOT_FOUND
  // ---------------------------------------------------------------------------
  it("unknown signWith → FAILED PRIVATE_KEY_NOT_FOUND", async () => {
    if (!goAvailable) return;

    const res = await submitSignTx("00000000-0000-0000-0000-000000000000", EIP1559_UNSIGNED_TX);
    expect(res.status).toBe(200);

    const json = (await res.json()) as {
      activity: { status: string; failure: { code: string } | null };
    };
    expect(json.activity.status).toBe("ACTIVITY_STATUS_FAILED");
    expect((json.activity.failure as { code: string } | null)?.code).toBe("PRIVATE_KEY_NOT_FOUND");
  });

  // ---------------------------------------------------------------------------
  // 4c. Malformed unsignedTransaction → FAILED
  // ---------------------------------------------------------------------------
  it("malformed unsignedTransaction → FAILED", async () => {
    if (!goAvailable) return;

    const { privateKeyId } = await submitCreateKey("p6-malformed-test");
    const res = await submitSignTx(privateKeyId, "0xdeadbeef_not_valid_rlp!@#");
    expect(res.status).toBe(200);

    const json = (await res.json()) as {
      activity: { status: string; failure: { code: string } | null };
    };
    expect(json.activity.status).toBe("ACTIVITY_STATUS_FAILED");
    expect(json.activity.failure).not.toBeNull();
  });

  // ---------------------------------------------------------------------------
  // 5. No plaintext in response or DB
  // ---------------------------------------------------------------------------
  it("no plaintext key in response or DB activity row", async () => {
    if (!goAvailable) return;

    const { privateKeyId } = await submitCreateKey("p6-noplain-test");
    const res = await submitSignTx(privateKeyId, EIP1559_UNSIGNED_TX);
    expect(res.status).toBe(200);

    const responseBody = await res.json();
    assertNoPlaintextKey(responseBody);

    const activityId = (responseBody as { activity: { id: string } }).activity.id;
    const row = await tdb.db
      .selectFrom("activities")
      .selectAll()
      .where("id", "=", activityId)
      .executeTakeFirst();

    expect(row).not.toBeUndefined();
    assertNoPlaintextKey(row!.result);
    assertNoPlaintextKey(row!.request_body);

    // signer receipt must be present in the stored result
    const result = row!.result as Record<string, unknown>;
    const signResult = result.signTransactionResult as Record<string, unknown> | undefined;
    expect(signResult).not.toBeUndefined();
    expect(signResult!.signerReceipt).not.toBeUndefined();
  });

  // ---------------------------------------------------------------------------
  // Wire shape: activity result matches wire-contract expectations
  // ---------------------------------------------------------------------------
  it("activity result shape: type, status, intent, result all present", async () => {
    if (!goAvailable) return;

    const { privateKeyId } = await submitCreateKey("p6-wireshape-test");
    const res = await submitSignTx(privateKeyId, EIP1559_UNSIGNED_TX);
    const json = (await res.json()) as {
      activity: {
        status: string;
        type: string;
        intent: Record<string, unknown>;
        result: { signTransactionResult: { signedTransaction: string } };
        failure: null;
        votes: unknown[];
        fingerprint: string;
      };
    };

    expect(json.activity.type).toBe("ACTIVITY_TYPE_SIGN_TRANSACTION_V2");
    expect(json.activity.status).toBe("ACTIVITY_STATUS_COMPLETED");
    expect(json.activity.failure).toBeNull();
    expect(typeof json.activity.intent.signTransactionIntent).toBe("object");
    expect(typeof json.activity.result.signTransactionResult).toBe("object");
    expect(typeof json.activity.result.signTransactionResult.signedTransaction).toBe("string");
  });
});
