package evmtx_test

import (
	"crypto/ecdsa"
	"encoding/hex"
	"math/big"
	"strings"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/rlp"

	"kryard/signer/internal/evmtx"
)

// testKey is a well-known secp256k1 private key (Ganache account #0).
// Private key: 0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
// Expected address: 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
const (
	testPrivHex    = "4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d"
	testKeyAddress = "0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"
	sepoliaChainID = int64(11155111)
)

// Fixed unsigned EIP-1559 tx (type 0x02) for chainId=11155111 (Sepolia):
//
//	nonce=0, maxPriorityFeePerGas=1e9, maxFeePerGas=1e9, gas=21000,
//	to=0x000000000000000000000000000000000000dEaD, value=0, data=[], accessList=[]
//
// Generated by encoding the 9-field RLP list with 0x02 type prefix.
const eip1559UnsignedHex = "0x02ea83aa36a780843b9aca00843b9aca0082520894000000000000000000000000000000000000dead8080c0"

// Fixed unsigned legacy EIP-155 tx for chainId=11155111:
//
//	nonce=0, gasPrice=1e9, gas=21000, to=0x...dEaD, value=0, data=[]
//	9-field form: [nonce, gasPrice, gas, to, value, data, chainId, 0, 0]
const legacyUnsignedHex = "0xe680843b9aca0082520894000000000000000000000000000000000000dead808083aa36a78080"

// loadTestKey returns the Ganache account #0 ecdsa.PrivateKey.
func loadTestKey(t *testing.T) *ecdsa.PrivateKey {
	t.Helper()
	privBytes, err := hex.DecodeString(testPrivHex)
	if err != nil {
		t.Fatalf("decode test private key: %v", err)
	}
	ecKey, err := crypto.ToECDSA(privBytes)
	if err != nil {
		t.Fatalf("ToECDSA: %v", err)
	}
	return ecKey
}

// recoverSender decodes a signed tx hex and recovers the sender address.
func recoverSender(t *testing.T, signedTxHex string, chainID *big.Int) string {
	t.Helper()

	hexStr := signedTxHex
	if strings.HasPrefix(hexStr, "0x") || strings.HasPrefix(hexStr, "0X") {
		hexStr = hexStr[2:]
	}
	raw, err := hex.DecodeString(hexStr)
	if err != nil {
		t.Fatalf("decode signed tx hex: %v", err)
	}

	var tx types.Transaction
	if err := tx.UnmarshalBinary(raw); err != nil {
		t.Fatalf("UnmarshalBinary signed tx: %v", err)
	}

	signer := types.LatestSignerForChainID(chainID)
	addr, err := types.Sender(signer, &tx)
	if err != nil {
		t.Fatalf("types.Sender: %v", err)
	}
	return addr.Hex()
}

// TestEIP1559SignAndRecover signs a fixed EIP-1559 unsigned tx with a known key
// and verifies the signature recovers to the key's address.
func TestEIP1559SignAndRecover(t *testing.T) {
	ecKey := loadTestKey(t)

	result, err := evmtx.SignUnsignedTx(eip1559UnsignedHex, ecKey)
	if err != nil {
		t.Fatalf("SignUnsignedTx EIP-1559: %v", err)
	}

	if !strings.HasPrefix(result.SignedTransaction, "0x") {
		t.Errorf("SignedTransaction missing 0x prefix: %q", result.SignedTransaction)
	}

	// Verify the signed tx recovers to the key's address.
	chainID := big.NewInt(sepoliaChainID)
	recovered := recoverSender(t, result.SignedTransaction, chainID)
	if !strings.EqualFold(recovered, testKeyAddress) {
		t.Errorf("recovered sender = %q, want %q", recovered, testKeyAddress)
	}
}

// TestEIP1559FieldExtraction verifies that the extracted fields match the
// values encoded in the fixed test vector.
func TestEIP1559FieldExtraction(t *testing.T) {
	ecKey := loadTestKey(t)

	result, err := evmtx.SignUnsignedTx(eip1559UnsignedHex, ecKey)
	if err != nil {
		t.Fatalf("SignUnsignedTx EIP-1559: %v", err)
	}

	f := result.Fields

	// ChainID = 11155111 = 0xaa36a7
	if !strings.EqualFold(f.ChainID, "0xaa36a7") {
		t.Errorf("ChainID = %q, want 0xaa36a7", f.ChainID)
	}
	// To = 0x000...dEaD (checksummed)
	if !strings.EqualFold(f.To, "0x000000000000000000000000000000000000dEaD") {
		t.Errorf("To = %q, want 0x000...dEaD", f.To)
	}
	// Value = 0
	if !strings.EqualFold(f.Value, "0x0") {
		t.Errorf("Value = %q, want 0x0", f.Value)
	}
	// Nonce = 0
	if f.Nonce != 0 {
		t.Errorf("Nonce = %d, want 0", f.Nonce)
	}
	// Gas = 21000 = 0x5208
	if f.Gas != 21000 {
		t.Errorf("Gas = %d, want 21000", f.Gas)
	}
	// MaxFeePerGas = 1e9 = 0x3b9aca00
	if !strings.EqualFold(f.MaxFeePerGas, "0x3b9aca00") {
		t.Errorf("MaxFeePerGas = %q, want 0x3b9aca00", f.MaxFeePerGas)
	}
	// MaxPriorityFeePerGas = 1e9 = 0x3b9aca00
	if !strings.EqualFold(f.MaxPriorityFeePerGas, "0x3b9aca00") {
		t.Errorf("MaxPriorityFeePerGas = %q, want 0x3b9aca00", f.MaxPriorityFeePerGas)
	}
	// Data = empty → "0x"
	if f.Data != "0x" {
		t.Errorf("Data = %q, want 0x", f.Data)
	}
	// MethodSelector = "" (data < 4 bytes)
	if f.MethodSelector != "" {
		t.Errorf("MethodSelector = %q, want empty string", f.MethodSelector)
	}
	// GasPrice should be empty for EIP-1559
	if f.GasPrice != "" {
		t.Errorf("GasPrice = %q, want empty for EIP-1559", f.GasPrice)
	}
}

// TestLegacyEIP155SignAndRecover signs a fixed legacy EIP-155 unsigned tx
// with a known key and verifies the signature recovers to the key's address.
func TestLegacyEIP155SignAndRecover(t *testing.T) {
	ecKey := loadTestKey(t)

	result, err := evmtx.SignUnsignedTx(legacyUnsignedHex, ecKey)
	if err != nil {
		t.Fatalf("SignUnsignedTx legacy: %v", err)
	}

	if !strings.HasPrefix(result.SignedTransaction, "0x") {
		t.Errorf("SignedTransaction missing 0x prefix: %q", result.SignedTransaction)
	}

	// Verify recovery.
	chainID := big.NewInt(sepoliaChainID)
	recovered := recoverSender(t, result.SignedTransaction, chainID)
	if !strings.EqualFold(recovered, testKeyAddress) {
		t.Errorf("legacy recovered sender = %q, want %q", recovered, testKeyAddress)
	}
}

// TestLegacyFieldExtraction verifies the extracted fields for the legacy tx.
func TestLegacyFieldExtraction(t *testing.T) {
	ecKey := loadTestKey(t)

	result, err := evmtx.SignUnsignedTx(legacyUnsignedHex, ecKey)
	if err != nil {
		t.Fatalf("SignUnsignedTx legacy: %v", err)
	}

	f := result.Fields

	// ChainID = 11155111 = 0xaa36a7
	if !strings.EqualFold(f.ChainID, "0xaa36a7") {
		t.Errorf("ChainID = %q, want 0xaa36a7", f.ChainID)
	}
	// GasPrice = 1e9 = 0x3b9aca00
	if !strings.EqualFold(f.GasPrice, "0x3b9aca00") {
		t.Errorf("GasPrice = %q, want 0x3b9aca00", f.GasPrice)
	}
	// MaxFeePerGas should be empty for legacy
	if f.MaxFeePerGas != "" {
		t.Errorf("MaxFeePerGas = %q, want empty for legacy", f.MaxFeePerGas)
	}
	// MaxPriorityFeePerGas should be empty for legacy
	if f.MaxPriorityFeePerGas != "" {
		t.Errorf("MaxPriorityFeePerGas = %q, want empty for legacy", f.MaxPriorityFeePerGas)
	}
}

// TestMethodSelectorExtraction verifies the first 4 bytes of calldata are extracted correctly.
func TestMethodSelectorExtraction(t *testing.T) {
	// Build an EIP-1559 unsigned tx with calldata starting 0x7fea8778 (sweep-like selector).
	ecKey := loadTestKey(t)

	// We construct a custom unsigned tx with 4+ bytes of calldata.
	// Use the helper to build raw bytes.
	chainID := big.NewInt(sepoliaChainID)

	// Build the 9-field list manually using types package for correctness.
	to := common.HexToAddress("0x000000000000000000000000000000000000dEaD")
	calldata := []byte{0x7f, 0xea, 0x87, 0x78, 0xab, 0xcd, 0xef, 0x01, 0x02, 0x03}

	inner := struct {
		ChainID              *big.Int
		Nonce                uint64
		MaxPriorityFeePerGas *big.Int
		MaxFeePerGas         *big.Int
		Gas                  uint64
		To                   []byte
		Value                *big.Int
		Data                 []byte
		AccessList           types.AccessList
	}{
		ChainID:              chainID,
		Nonce:                1,
		MaxPriorityFeePerGas: big.NewInt(1_000_000_000),
		MaxFeePerGas:         big.NewInt(1_000_000_000),
		Gas:                  100_000,
		To:                   to.Bytes(),
		Value:                big.NewInt(0),
		Data:                 calldata,
		AccessList:           types.AccessList{},
	}

	encoded, err := rlp.EncodeToBytes(inner)
	if err != nil {
		t.Fatalf("rlp.EncodeToBytes: %v", err)
	}
	txBytes := append([]byte{0x02}, encoded...)
	txHex := "0x" + hex.EncodeToString(txBytes)

	result, err := evmtx.SignUnsignedTx(txHex, ecKey)
	if err != nil {
		t.Fatalf("SignUnsignedTx with calldata: %v", err)
	}

	if result.Fields.MethodSelector != "0x7fea8778" {
		t.Errorf("MethodSelector = %q, want 0x7fea8778", result.Fields.MethodSelector)
	}

	// Data should start with the full calldata.
	if !strings.HasPrefix(result.Fields.Data, "0x7fea8778") {
		t.Errorf("Data = %q, want 0x7fea8778... prefix", result.Fields.Data)
	}

	// Recovery must still work.
	recovered := recoverSender(t, result.SignedTransaction, chainID)
	if !strings.EqualFold(recovered, testKeyAddress) {
		t.Errorf("recovered sender with calldata = %q, want %q", recovered, testKeyAddress)
	}
}

// TestMalformedHexReturnsError ensures malformed input returns an error gracefully.
func TestMalformedHexReturnsError(t *testing.T) {
	ecKey := loadTestKey(t)

	_, err := evmtx.SignUnsignedTx("0xnotvalidhex!@#$", ecKey)
	if err == nil {
		t.Error("expected error for malformed hex, got nil")
	}
}

// TestEmptyInputReturnsError ensures empty input returns an error.
func TestEmptyInputReturnsError(t *testing.T) {
	ecKey := loadTestKey(t)

	_, err := evmtx.SignUnsignedTx("", ecKey)
	if err == nil {
		t.Error("expected error for empty input, got nil")
	}
}

// TestEIP1559SignedTxHasTypePrefix verifies the signed EIP-1559 tx starts with 0x02.
func TestEIP1559SignedTxHasTypePrefix(t *testing.T) {
	ecKey := loadTestKey(t)

	result, err := evmtx.SignUnsignedTx(eip1559UnsignedHex, ecKey)
	if err != nil {
		t.Fatalf("SignUnsignedTx: %v", err)
	}

	// After stripping 0x, first byte should be 0x02 for EIP-1559.
	hexStr := strings.TrimPrefix(result.SignedTransaction, "0x")
	if len(hexStr) < 2 || hexStr[:2] != "02" {
		t.Errorf("signed EIP-1559 tx should start with 0x02, got prefix %q", hexStr[:min(4, len(hexStr))])
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
